default["mysql"]["root_password"] = '1140986k'
default["mysql"]["db_name"] = 'wordpress'
default["mysql"]["user"]["name"] = 'wordpress'
default["mysql"]["user"]["password"] = '1140986k'
default["mysql"]["hostname"] = 'localhost'
default['http']['doc_root'] = '/home/vitualdomain/'
default['http']['server_name'] = 'ec2-52-198-160-173.ap-northeast-1.compute.amazonaws.com'
